/** 標準錯誤代碼 */
export const ErrorCodes = {
  NO_CONFIG: 'NO_CONFIG',
  NO_SESSION: 'NO_SESSION',
  JWT_EXPIRED: 'JWT_EXPIRED',
  AUTH_FAILED: 'AUTH_FAILED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  FETCH_FAILED: 'FETCH_FAILED',
  DB_ERROR: 'DB_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  STORAGE_FAILED: 'STORAGE_FAILED',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  LINE_AUTH_FAILED: 'LINE_AUTH_FAILED',
  GOOGLE_AUTH_FAILED: 'GOOGLE_AUTH_FAILED',
  APPLE_AUTH_FAILED: 'APPLE_AUTH_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',
  VALIDATION_ERROR: 'VALIDATION_ERROR'
};
